docs: updated welcome page and changed sdk docs for seo
fern-api/fern pull request #3802
Opened 2024-06-06 21:39 UTC by atwooddc

2024-06-06 21:39 UTC, atwooddc commented
preview: https://fern-beta-preview-82641906-6bb2-48b7-8717-22b88571a394.docs.buildwithfern.com

2024-06-08 21:24 UTC, dannysheridan requested changes

2024-06-08 21:24 UTC, dannysheridan commented on fern/pages/sdks/introduction/what-is-an-sdk.mdx
> +<CodeBlocks maxLines={10}>
Can you add TypeScript and C#? If you need to generate the SDK locally to see what the code looks like in each language, you should do that. Doesn't look like Ruby, Java, or Go are using SDK code (instead they're using HTTP calls directly now)

Order should be: TypeScript, Python, Go, Java, Ruby, C#

2024-06-08 21:24 UTC, dannysheridan commented on fern/pages/sdks/introduction/what-is-an-sdk.mdx
> +### SDKs vs. vanilla code
What does "vanilla code" mean? It's fair to assume a developer has not heard of this term.

2024-06-08 21:24 UTC, dannysheridan commented on fern/pages/sdks/introduction/what-is-an-sdk.mdx
> +As an example, compare vanilla TypeScript with the Fern SDK to convert text to speech via the ElevenLabs API:
the term "Fern SDK" feels ambiguous to me. 

compare vanilla TypeScript (i.e., using `fetch` to make an HTTP call) with a TypeScript SDK generated by Fern ...

2024-06-08 21:24 UTC, dannysheridan commented on fern/pages/sdks/introduction/what-is-an-sdk.mdx
> +As an example, compare vanilla TypeScript with the Fern SDK to convert text to speech via the ElevenLabs API:
could also say "built with Fern" if you want to lean into that branding

2024-06-08 21:24 UTC, dannysheridan commented on fern/pages/welcome.mdx
> +  We built Fern to productize this process and make it accessible. Just input an OpenAPI
APIs underpin the internet but are still painful to work with. They are often untyped, unstandardized, and out-of-sync across multiple sources of truth.

While companies like Stripe, Twilio, and AWS have the resources to develop internal tools for developer experience. Not all businesses have this advantage.

That's why we are building Fern. Fern allows engineering teams to offer developer-friendly APIs, including easy-to-use SDKs and up-to-date developer documentation.

2024-06-17 17:39 UTC, atwooddc commented
Preview: https://fern-beta-preview-f2a58806-465b-41a3-a878-a6dde0153493.docs.buildwithfern.com

2024-08-12 12:20 UTC, closed without merging